# Introduction:

The sustainable management of tuna and other highly migratory fish stocks is critical to ensure the long-term viability of these important resources. Regional fisheries management organizations (RFMOs) play a key role in collecting and analyzing data on tuna catches, fishing effort, and other relevant factors to inform their decisions on sustainable management. However, concerns have been raised about the accuracy and reliability of some of the data provided by the RFMOs, particularly in relation to the location of fishing activities and the potential for double reporting in overlapping zones.

To address these concerns, the Institut de Recherche pour le Développement (IRD), in collaboration with the Food and Agriculture Organization of the United Nations (FAO) and the RFMOs, has developed the Global Tuna Atlas (GTA). The GTA is a platform that integrates data from various sources to provide more accurate and reliable information on the distribution and abundance of tuna stocks worldwide.

As part of the GTA project, IRD has identified mislocated data provided by the RFMOs and has undertaken a comprehensive analysis to correct and validate these data. In addition, we have also analyzed the potential for double reporting of data in overlapping zones between RFMOs. Our analysis shows that double reporting can lead to overestimation of tuna stocks, which can have negative impacts on the sustainable management of these important resources. However, handling overlapping zone by keeping only one of the data source as it was done before can create removing of consistent and unique data.

In this paper, we present the results of our analysis of mislocated data and double reporting in the RFMOs' data. We also discuss the steps that can be taken to address these issues and improve the accuracy and reliability of the data used to inform management decisions. We believe that our findings will be of great value to the RFMOs and other stakeholders involved in the sustainable management of tuna stocks. By improving the accuracy and reliability of the data, we can work towards ensuring the long-term sustainability of these important fish populations.

The results presented are to help tRFMOs identify the potential issues and/or provide answers to the wondering about these data. The detail list of mislocated catches will be send in another document provided to each tRFMO data manager.

